"use client";

import { useState } from "react";
import { Loader2, Sparkles, CheckCircle, Download, ExternalLink, Construction, ListTodo, FileText, ShoppingCart } from "lucide-react";
import JSZip from "jszip";
import { saveAs } from "file-saver";

const templates = [
  { id: "construction", name: "Construction Dashboard", icon: Construction, prompt: "Build a construction job management dashboard with job tracking, client management, quote generation, and scheduling calendar" },
  { id: "todo", name: "Todo App", icon: ListTodo, prompt: "Build a todo app with categories, due dates, priority levels, and the ability to share lists" },
  { id: "blog", name: "Blog CMS", icon: FileText, prompt: "Build a blog with markdown support, categories, tags, and an admin dashboard" },
  { id: "ecommerce", name: "E-commerce", icon: ShoppingCart, prompt: "Build an e-commerce store with product catalog, shopping cart, and checkout flow" },
];

type GenerationStatus = "idle" | "analyzing" | "planning" | "generating" | "validating" | "complete" | "error";

interface GenerationResult {
  requirements?: {
    name: string;
    description: string;
    features: string[];
  };
  stats?: {
    totalFiles: number;
    components: number;
    routes: number;
  };
  files?: Array<{
    path: string;
    content: string;
  }>;
  error?: string;
}

export function PromptBuilder() {
  const [prompt, setPrompt] = useState("");
  const [status, setStatus] = useState<GenerationStatus>("idle");
  const [result, setResult] = useState<GenerationResult | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim() || prompt.length < 10) return;

    setStatus("analyzing");
    setResult(null);

    try {
      // Simulate status progression for UX
      setTimeout(() => setStatus("planning"), 2000);
      setTimeout(() => setStatus("generating"), 5000);
      setTimeout(() => setStatus("validating"), 12000);

      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Generation failed");
      }

      setResult(data);
      setStatus("complete");
    } catch (error) {
      console.error("Generation error:", error);
      setResult({ error: error instanceof Error ? error.message : "Generation failed" });
      setStatus("error");
    }
  };

  const handleTemplateClick = (templatePrompt: string) => {
    setPrompt(templatePrompt);
  };

  const handleDownload = async () => {
    if (!result?.files || result.files.length === 0) return;

    const zip = new JSZip();
    const projectName = result.requirements?.name || "generated-app";

    // Add each file to the zip
    for (const file of result.files) {
      zip.file(file.path, file.content);
    }

    // Add a README
    const readme = `# ${projectName}

Generated by Looplet Builder

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000)

## Files Generated

${result.files.map(f => `- ${f.path}`).join('\n')}
`;
    zip.file("README.md", readme);

    // Generate and download
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, `${projectName.toLowerCase().replace(/\s+/g, "-")}.zip`);
  };

  const isGenerating = ["analyzing", "planning", "generating", "validating"].includes(status);

  return (
    <div className="glass rounded-2xl p-8">
      {/* Templates */}
      <div className="mb-6">
        <p className="text-sm text-gray-400 mb-3">Quick Start Templates:</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {templates.map((template) => (
            <button
              key={template.id}
              onClick={() => handleTemplateClick(template.prompt)}
              disabled={isGenerating}
              className="flex flex-col items-center gap-2 p-4 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 hover:border-blue-500/50 transition-all disabled:opacity-50"
            >
              <template.icon className="w-6 h-6 text-blue-400" />
              <span className="text-xs text-gray-300">{template.name}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Prompt Input */}
      <div className="mb-6">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe your app... e.g., 'Build a project management tool for construction teams with job tracking, client management, and invoice generation'"
          disabled={isGenerating}
          className="w-full h-32 p-4 rounded-xl bg-white/5 border border-white/10 focus:border-blue-500/50 focus:outline-none text-white placeholder-gray-500 resize-none disabled:opacity-50"
        />
        <div className="flex justify-between items-center mt-2">
          <span className="text-xs text-gray-500">{prompt.length} characters</span>
          <span className="text-xs text-gray-500">Minimum 10 characters</span>
        </div>
      </div>

      {/* Generate Button */}
      <button
        onClick={handleGenerate}
        disabled={isGenerating || prompt.length < 10}
        className="w-full py-4 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white font-semibold flex items-center justify-center gap-2 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {isGenerating ? (
          <>
            <Loader2 className="w-5 h-5 animate-spin" />
            <span>{getStatusText(status)}</span>
          </>
        ) : (
          <>
            <Sparkles className="w-5 h-5" />
            <span>Generate App</span>
          </>
        )}
      </button>

      {/* Progress Steps */}
      {isGenerating && (
        <div className="mt-6 space-y-3">
          <ProgressStep label="Analyzing prompt" status={getStepStatus("analyzing", status)} />
          <ProgressStep label="Planning architecture" status={getStepStatus("planning", status)} />
          <ProgressStep label="Generating code" status={getStepStatus("generating", status)} />
          <ProgressStep label="Validating output" status={getStepStatus("validating", status)} />
        </div>
      )}

      {/* Results */}
      {status === "complete" && result && (
        <div className="mt-6 p-6 rounded-xl bg-green-500/10 border border-green-500/20">
          <div className="flex items-center gap-2 mb-4">
            <CheckCircle className="w-5 h-5 text-green-400" />
            <span className="text-green-400 font-semibold">Generation Complete!</span>
          </div>

          {result.requirements && (
            <div className="mb-4">
              <h4 className="text-white font-medium mb-2">{result.requirements.name}</h4>
              <p className="text-gray-400 text-sm">{result.requirements.description}</p>
            </div>
          )}

          {result.stats && (
            <div className="grid grid-cols-3 gap-4 mb-4">
              <div className="text-center p-3 rounded-lg bg-white/5">
                <div className="text-2xl font-bold text-white">{result.stats.totalFiles}</div>
                <div className="text-xs text-gray-400">Files</div>
              </div>
              <div className="text-center p-3 rounded-lg bg-white/5">
                <div className="text-2xl font-bold text-white">{result.stats.components}</div>
                <div className="text-xs text-gray-400">Components</div>
              </div>
              <div className="text-center p-3 rounded-lg bg-white/5">
                <div className="text-2xl font-bold text-white">{result.stats.routes}</div>
                <div className="text-xs text-gray-400">Routes</div>
              </div>
            </div>
          )}

          <div className="flex gap-3">
            <button
              onClick={handleDownload}
              className="flex-1 py-3 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-medium flex items-center justify-center gap-2 transition-colors"
            >
              <Download className="w-4 h-4" />
              Download Code
            </button>
            <button className="flex-1 py-3 rounded-lg bg-white/10 hover:bg-white/20 text-white font-medium flex items-center justify-center gap-2 transition-colors">
              <ExternalLink className="w-4 h-4" />
              Deploy to Vercel
            </button>
          </div>
        </div>
      )}

      {/* Error */}
      {status === "error" && result?.error && (
        <div className="mt-6 p-6 rounded-xl bg-red-500/10 border border-red-500/20">
          <p className="text-red-400">{result.error}</p>
          <button
            onClick={() => setStatus("idle")}
            className="mt-4 px-4 py-2 rounded-lg bg-red-500/20 hover:bg-red-500/30 text-red-400 transition-colors"
          >
            Try Again
          </button>
        </div>
      )}
    </div>
  );
}

function getStatusText(status: GenerationStatus): string {
  switch (status) {
    case "analyzing": return "Analyzing your prompt...";
    case "planning": return "Planning architecture...";
    case "generating": return "Generating code...";
    case "validating": return "Validating output...";
    default: return "Processing...";
  }
}

function getStepStatus(step: GenerationStatus, currentStatus: GenerationStatus): "pending" | "active" | "complete" {
  const steps: GenerationStatus[] = ["analyzing", "planning", "generating", "validating"];
  const stepIndex = steps.indexOf(step);
  const currentIndex = steps.indexOf(currentStatus);

  if (stepIndex < currentIndex) return "complete";
  if (stepIndex === currentIndex) return "active";
  return "pending";
}

function ProgressStep({ label, status }: { label: string; status: "pending" | "active" | "complete" }) {
  return (
    <div className="flex items-center gap-3">
      <div className={`w-6 h-6 rounded-full flex items-center justify-center ${
        status === "complete" ? "bg-green-500" :
        status === "active" ? "bg-blue-500" :
        "bg-gray-700"
      }`}>
        {status === "complete" ? (
          <CheckCircle className="w-4 h-4 text-white" />
        ) : status === "active" ? (
          <Loader2 className="w-4 h-4 text-white animate-spin" />
        ) : (
          <div className="w-2 h-2 rounded-full bg-gray-500" />
        )}
      </div>
      <span className={`text-sm ${
        status === "complete" ? "text-green-400" :
        status === "active" ? "text-blue-400" :
        "text-gray-500"
      }`}>
        {label}
      </span>
    </div>
  );
}
